steps:
  # 1. Build the docker container image
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - >-
        ${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/${_IMAGE_NAME}:${_GIT_TAG}
      - .
    id: Build Docker Image
  # 2. Push the container to the registry
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        ${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/${_IMAGE_NAME}:${_GIT_TAG}
    id: Push to Artifact Registry
images:
  - >-
    ${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/${_IMAGE_NAME}:${_GIT_TAG}
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
